name: 'Pnpm install'
description: 'Install pnpm with cache'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  directory:
    description: 'Working directory'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: pnpm install